/// Flutter icons SdSbIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SdSbIcons
///      fonts:
///       - asset: fonts/SdSbIcons.ttf
///
///
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class SdSbIcons {
  SdSbIcons._();

  static const _kFontFam = 'SdSbIcons';
  static const String? _kFontPkg = null;

  static const IconData search =
      IconData(0xf002, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag =
      IconData(0xf02b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronLeft =
      IconData(0xf053, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronRight =
      IconData(0xf054, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowUp =
      IconData(0xf062, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowDown =
      IconData(0xf063, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowCircleUp =
      IconData(0xf0aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowCircleDown =
      IconData(0xf0ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter =
      IconData(0xf0b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dollarSign =
      IconData(0xf155, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
